# Generated by Django 5.1.3 on 2025-09-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lang',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
